# Generated by Django 2.0.2 on 2018-02-22 05:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0004_auto_20180221_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileDownloadRec',
            new_name='FileRec',
        ),
    ]
