# Generated by Django 2.0.2 on 2018-02-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20180222_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='filerec',
            name='type',
            field=models.CharField(choices=[('U', 'upload'), ('D', 'download'), ('R', 'delete'), ('S', 'share')], max_length=1),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='share_opt',
            field=models.BooleanField(primary_key='False', serialize=False),
        ),
    ]
