# Generated by Django 2.0.2 on 2018-02-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20180224_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_opt', models.BooleanField(primary_key='False', serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='share_opt',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.UploadFile'),
        ),
    ]
